### ISSUE TITLE
BF4: Exception in frostbiteClientMessageQueueWorker

### ISSUE THREAD

**Issue by thomasleveil** [BigBrotherBot/big-brother-bot#348]
The following error [was reported](http://forum.bigbrotherbot.net/general-usage-support/error-'stderr-'exception-in-thread-client-(bf3-server)/msg46506/#msg46506) on the forums for B3 v1.10.1:

```
STDERR 'Exception in thread Client<@2:EA_E134A3C9DA686275C48C4346779512AE|0827695e1130b4f2cdb429d7c30ff1f6:"ZzSonozZ":ZzSonozZ>_messagehandler:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
  File "C:\Python27\lib\threading.py", line 763, in run
  File "c:\jenkins_slave\workspace\B3-1.10-dist-daily\b3\parsers\frostbite2\abstractParser.py", line 1792, in frostbiteClientMessageQueueWorker

AttributeError: 'Bf3Parser' object has no attribute '_settings'
```

**Comment by thomasleveil** [comment]
regression introduced with commit a6b9a19885 and in particular [this](https://github.com/BigBrotherBot/big-brother-bot/commit/a6b9a198854353b6d56a40df6bf9424a3a6e9708#diff-ba862cba2a1e26c3a90838a9487c7e70R115) change.

at https://github.com/BigBrotherBot/big-brother-bot/blob/release-1.10/b3/parsers/frostbite2/abstractParser.py#L1793 `time.sleep(float(self.console._settings.get('message_delay', 1)))` should now be:

 ```python
if hasattr(self.console, 'message_delay'):
    message_delay = self.console.message_delay
else:
    message_delay = 1
time.sleep(float(self.console.message_delay))
```
